// Code generated by mockery 2.9.0. DO NOT EDIT.

package automock

import (
	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"

	rest "k8s.io/client-go/rest"
)

// K8sClientProvider is an autogenerated mock type for the K8sClientProvider type
type K8sClientProvider struct {
	mock.Mock
}

// InitClient provides a mock function with given fields: cfg
func (_m *K8sClientProvider) InitClient(cfg *rest.Config) (client.Client, error) {
	ret := _m.Called(cfg)

	var r0 client.Client
	if rf, ok := ret.Get(0).(func(*rest.Config) client.Client); ok {
		r0 = rf(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*rest.Config) error); ok {
		r1 = rf(cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
