apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc-kubeconfig-service.fullname" . }}
  labels:
{{ include "oidc-kubeconfig-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oidc-kubeconfig-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oidc-kubeconfig-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{ if .Values.global.isLocalEnv }}
      hostAliases:
        - ip: {{ .Values.global.minikubeIP }}
          hostnames:
            - "dex.{{ .Values.global.ingress.domainName }}"
      {{ end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "oidc-kubeconfig-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: PORT_SERVICE
              value: {{ .Values.config.servicePort | quote }}
            - name: PORT_HEALTH
              value: {{ .Values.config.healthPort | quote }}
            - name: GRAPHQL_URL
              value: {{ .Values.config.graphqlURL | quote }}
            - name: OIDC_KUBECONFIG_ISSUER_URL
              value: {{ .Values.config.oidc.kubeconfig.issuer | quote }}
            - name: OIDC_KUBECONFIG_CLIENT_ID
              value: {{ .Values.config.oidc.kubeconfig.client | quote }}
            - name: OIDC_ISSUER_URL
              value: {{ tpl .Values.config.oidc.issuer $ | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.config.oidc.client }}
            {{- with .Values.config.oidc.caFile }}
            - name: OIDC_CA
              value: {{ . }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.servicePort }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.config.healthPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/ready
              port: health
            initialDelaySeconds: {{ .Values.global.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.global.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.global.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: health
            initialDelaySeconds: {{ .Values.global.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.global.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.global.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: dex-tls-cert
              mountPath: /etc/dex-tls-cert/
      volumes:
        - name: dex-tls-cert
          secret:
            secretName: ingress-tls-cert
            optional: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
