{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1beta1" }}
---
apiVersion: networking.istio.io/v1abeta1
kind: VirtualService
metadata:
  name: {{ template "oidc-kubeconfig-service.fullname" . }}
  labels:
{{ include "oidc-kubeconfig-service.labels" . | indent 4 }}
spec:
  hosts:
    - {{ .Values.service.hostname }}.{{ .Values.global.ingress.domainName }}
  gateways:
    - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
    {{- if .Values.global.istio.additionalGateways }}
    {{ toYaml .Values.global.istio.additionalGateways | nindent 4 }}
    {{- end }}
  http:
    - match:
        - uri:
            regex: /.*
      route:
        - destination:
            port:
              number: {{ .Values.config.servicePort }}
            host: {{ template "oidc-kubeconfig-service.fullname" . }}
      corsPolicy:
        allowHeaders:
        - authorization
        - content-type
        allowMethods:
        - GET
        allowOrigins:
        - regex: ".*"
{{- end }}
