{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metris.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
{{ include "metris.labels" . | indent 4 }}
{{- end }}