// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, shoot, opts
func (_m *Client) Create(ctx context.Context, shoot *v1beta1.Shoot, opts v1.CreateOptions) (*v1beta1.Shoot, error) {
	ret := _m.Called(ctx, shoot, opts)

	var r0 *v1beta1.Shoot
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Shoot, v1.CreateOptions) *v1beta1.Shoot); ok {
		r0 = rf(ctx, shoot, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.Shoot)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1beta1.Shoot, v1.CreateOptions) error); ok {
		r1 = rf(ctx, shoot, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *Client) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Shoot, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *v1beta1.Shoot
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *v1beta1.Shoot); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.Shoot)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, shoot, opts
func (_m *Client) Update(ctx context.Context, shoot *v1beta1.Shoot, opts v1.UpdateOptions) (*v1beta1.Shoot, error) {
	ret := _m.Called(ctx, shoot, opts)

	var r0 *v1beta1.Shoot
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Shoot, v1.UpdateOptions) *v1beta1.Shoot); ok {
		r0 = rf(ctx, shoot, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.Shoot)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1beta1.Shoot, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, shoot, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
