// Code generated by mockery v2.14.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// PlanValidator is an autogenerated mock type for the PlanValidator type
type PlanValidator struct {
	mock.Mock
}

// IsPlanSupport provides a mock function with given fields: planID
func (_m *PlanValidator) IsPlanSupport(planID string) bool {
	ret := _m.Called(planID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(planID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewPlanValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewPlanValidator creates a new instance of PlanValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPlanValidator(t mockConstructorTestingTNewPlanValidator) *PlanValidator {
	mock := &PlanValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
