apiVersion: v1
kind: Service
metadata:
  labels:
    app: metris-poc
  name: metris-poc
  namespace: kcp-system
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: metris-poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metris-poc
  name: metris-poc
  namespace: kcp-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: metris-poc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: “false”
      labels:
        app: metris-poc
    spec:
      containers:
      - image: ko://github.com/kyma-project/control-plane/components/metris-poc/cmd
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        name: metris-poc
        env:
          - name: GARDENER_KUBECONFIG
            value: /gardener/kubeconfig
          - name: KEB_ENDPOINT
            value: http://kcp-kyma-environment-broker.kcp-system:8080
        volumeMounts:
          - mountPath: /gardener
            name: gardener-kubeconfig
            readOnly: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gardener-kubeconfig
        secret:
          secretName: gardener-credentials
