{
 "title": "KCP/Provisioner",
 "tags": [
  "kyma",
  "kcp"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "component", "query": "kcp-provisioner-metrics" }
  ]
 },
 "panels": [
  {
   "title": "Provisioning Operations In Progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "SUM(kcp_provisioner_in_progress_provision_operations_total)",
     "legendFormat": "operations"
    }
   ]
  },
  {
   "title": "Deprovisioning Operations In Progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "SUM(kcp_provisioner_in_progress_deprovision_operations_total)"
    }
   ]
  },
  {
   "title": "Upgrade Operations In Progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "SUM(kcp_provisioner_in_progress_upgrade_operations_total)"
    }
   ]
  },
  {
   "title": "Sum of memory usage by container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (container_memory_usage_bytes{job=\"kubelet\",pod=~\"kcp-provisioner-.*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "{{ container }} - Current"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{pod=~\"kcp-provisioner-.*\"})",
     "legendFormat": "{{container}} - Requests"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{pod=~\"kcp-provisioner-.*\"})",
     "legendFormat": "{{container}} - Limit"
    }
   ]
  },
  {
   "title": "Sum of CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"kcp-provisioner-.*\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "{{container}} - Current"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{pod=~\"kcp-provisioner-.*\"})",
     "legendFormat": "{{container}} - Requests"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_cpu_cores{pod=~\"kcp-provisioner-.*\"})",
     "legendFormat": "{{container}} - Limit"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"$component\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{pod=~\"kcp-provisioner-.*\"}[1m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gothreads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"$component\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go memstats by pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"$component\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"$component\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"$component\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"$component\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=\"$component\"}",
     "legendFormat": "Open FDS {{pod}}"
    },
    {
     "expr": "process_max_fds{service=\"$component\"}",
     "legendFormat": "Max FDS"
    }
   ]
  },
  {
   "title": "GC duration [s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{service=\"$component\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "GC CPU Usage",
   "type": "graph",
   "description": "The fraction of this program's available CPU time used by the GC since the program started.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "application CPU fractrion" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{service=\"$component\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}