// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import gqlschema "github.com/kyma-project/control-plane/components/provisioner/pkg/gqlschema"
import hyperscaler "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/hyperscaler"
import mock "github.com/stretchr/testify/mock"

// AccountProvider is an autogenerated mock type for the AccountProvider type
type AccountProvider struct {
	mock.Mock
}

// GardenerCredentials provides a mock function with given fields: hyperscalerType, tenantName
func (_m *AccountProvider) GardenerCredentials(hyperscalerType hyperscaler.Type, tenantName string) (hyperscaler.Credentials, error) {
	ret := _m.Called(hyperscalerType, tenantName)

	var r0 hyperscaler.Credentials
	if rf, ok := ret.Get(0).(func(hyperscaler.Type, string) hyperscaler.Credentials); ok {
		r0 = rf(hyperscalerType, tenantName)
	} else {
		r0 = ret.Get(0).(hyperscaler.Credentials)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(hyperscaler.Type, string) error); ok {
		r1 = rf(hyperscalerType, tenantName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GardenerSecretName provides a mock function with given fields: input, tenantName
func (_m *AccountProvider) GardenerSecretName(input *gqlschema.GardenerConfigInput, tenantName string) (string, error) {
	ret := _m.Called(input, tenantName)

	var r0 string
	if rf, ok := ret.Get(0).(func(*gqlschema.GardenerConfigInput, string) string); ok {
		r0 = rf(input, tenantName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gqlschema.GardenerConfigInput, string) error); ok {
		r1 = rf(input, tenantName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GardenerSharedCredentials provides a mock function with given fields: hyperscalerType
func (_m *AccountProvider) GardenerSharedCredentials(hyperscalerType hyperscaler.Type) (hyperscaler.Credentials, error) {
	ret := _m.Called(hyperscalerType)

	var r0 hyperscaler.Credentials
	if rf, ok := ret.Get(0).(func(hyperscaler.Type) hyperscaler.Credentials); ok {
		r0 = rf(hyperscalerType)
	} else {
		r0 = ret.Get(0).(hyperscaler.Credentials)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(hyperscaler.Type) error); ok {
		r1 = rf(hyperscalerType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkUnusedSecretAsDirty provides a mock function with given fields: hyperscalerType, tenantName
func (_m *AccountProvider) MarkUnusedSecretAsDirty(hyperscalerType hyperscaler.Type, tenantName string) error {
	ret := _m.Called(hyperscalerType, tenantName)

	var r0 error
	if rf, ok := ret.Get(0).(func(hyperscaler.Type, string) error); ok {
		r0 = rf(hyperscalerType, tenantName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
