{{- if and .Values.metrics.enabled (and .Values.metrics.prometheusRule.enabled .Values.metrics.prometheusRule.rules) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "metris.fullname" . }}
{{- with .Values.metrics.prometheusRule.namespace }}
  namespace: {{ . }}
{{- end }}
  labels:
{{- with .Values.metrics.prometheusRule.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.metrics.prometheusRule.rules }}
  groups:
{{- range $name, $rules := .Values.metrics.prometheusRule.rules | fromYaml }}
    - name: {{ $name }}
      rules:
{{ toYaml $rules | indent 8 }}
{{- end }}
{{- end }}
{{- end }}