// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CisClient is an autogenerated mock type for the CisClient type
type CisClient struct {
	mock.Mock
}

// FetchSubAccountsToDelete provides a mock function with given fields:
func (_m *CisClient) FetchSubAccountsToDelete() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCisClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewCisClient creates a new instance of CisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCisClient(t mockConstructorTestingTNewCisClient) *CisClient {
	mock := &CisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
