// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/kyma-project/control-plane/components/provisioner/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ReleaseDownloader is an autogenerated mock type for the ReleaseDownloader type
type ReleaseDownloader struct {
	mock.Mock
}

// DownloadRelease provides a mock function with given fields: version
func (_m *ReleaseDownloader) DownloadRelease(version string) (model.Release, error) {
	ret := _m.Called(version)

	var r0 model.Release
	if rf, ok := ret.Get(0).(func(string) model.Release); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Get(0).(model.Release)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
