// Package mothership provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package mothership

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostClusters request with any body
	PostClustersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostClusters(ctx context.Context, body PostClustersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutClusters request with any body
	PutClustersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutClusters(ctx context.Context, body PutClustersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteClustersRuntimeID request
	DeleteClustersRuntimeID(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClustersRuntimeIDConfigConfigVersionStatus request
	GetClustersRuntimeIDConfigConfigVersionStatus(ctx context.Context, runtimeID string, configVersion string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClustersRuntimeIDStatus request
	GetClustersRuntimeIDStatus(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutClustersRuntimeIDStatus request with any body
	PutClustersRuntimeIDStatusWithBody(ctx context.Context, runtimeID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutClustersRuntimeIDStatus(ctx context.Context, runtimeID string, body PutClustersRuntimeIDStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClustersRuntimeIDStatusChanges request
	GetClustersRuntimeIDStatusChanges(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOperationsSchedulingIDCorrelationIDStop request with any body
	PostOperationsSchedulingIDCorrelationIDStopWithBody(ctx context.Context, schedulingID string, correlationID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOperationsSchedulingIDCorrelationIDStop(ctx context.Context, schedulingID string, correlationID string, body PostOperationsSchedulingIDCorrelationIDStopJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReconciliations request
	GetReconciliations(ctx context.Context, params *GetReconciliationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReconciliationsSchedulingIDInfo request
	GetReconciliationsSchedulingIDInfo(ctx context.Context, schedulingID string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostClustersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostClustersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostClusters(ctx context.Context, body PostClustersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostClustersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutClustersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutClustersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutClusters(ctx context.Context, body PutClustersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutClustersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteClustersRuntimeID(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteClustersRuntimeIDRequest(c.Server, runtimeID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClustersRuntimeIDConfigConfigVersionStatus(ctx context.Context, runtimeID string, configVersion string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClustersRuntimeIDConfigConfigVersionStatusRequest(c.Server, runtimeID, configVersion)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClustersRuntimeIDStatus(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClustersRuntimeIDStatusRequest(c.Server, runtimeID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutClustersRuntimeIDStatusWithBody(ctx context.Context, runtimeID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutClustersRuntimeIDStatusRequestWithBody(c.Server, runtimeID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutClustersRuntimeIDStatus(ctx context.Context, runtimeID string, body PutClustersRuntimeIDStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutClustersRuntimeIDStatusRequest(c.Server, runtimeID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClustersRuntimeIDStatusChanges(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClustersRuntimeIDStatusChangesRequest(c.Server, runtimeID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOperationsSchedulingIDCorrelationIDStopWithBody(ctx context.Context, schedulingID string, correlationID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOperationsSchedulingIDCorrelationIDStopRequestWithBody(c.Server, schedulingID, correlationID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOperationsSchedulingIDCorrelationIDStop(ctx context.Context, schedulingID string, correlationID string, body PostOperationsSchedulingIDCorrelationIDStopJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOperationsSchedulingIDCorrelationIDStopRequest(c.Server, schedulingID, correlationID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetReconciliations(ctx context.Context, params *GetReconciliationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReconciliationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetReconciliationsSchedulingIDInfo(ctx context.Context, schedulingID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReconciliationsSchedulingIDInfoRequest(c.Server, schedulingID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostClustersRequest calls the generic PostClusters builder with application/json body
func NewPostClustersRequest(server string, body PostClustersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostClustersRequestWithBody(server, "application/json", bodyReader)
}

// NewPostClustersRequestWithBody generates requests for PostClusters with any type of body
func NewPostClustersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutClustersRequest calls the generic PutClusters builder with application/json body
func NewPutClustersRequest(server string, body PutClustersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutClustersRequestWithBody(server, "application/json", bodyReader)
}

// NewPutClustersRequestWithBody generates requests for PutClusters with any type of body
func NewPutClustersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteClustersRuntimeIDRequest generates requests for DeleteClustersRuntimeID
func NewDeleteClustersRuntimeIDRequest(server string, runtimeID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "runtimeID", runtime.ParamLocationPath, runtimeID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClustersRuntimeIDConfigConfigVersionStatusRequest generates requests for GetClustersRuntimeIDConfigConfigVersionStatus
func NewGetClustersRuntimeIDConfigConfigVersionStatusRequest(server string, runtimeID string, configVersion string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "runtimeID", runtime.ParamLocationPath, runtimeID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "configVersion", runtime.ParamLocationPath, configVersion)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s/config/%s/status", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClustersRuntimeIDStatusRequest generates requests for GetClustersRuntimeIDStatus
func NewGetClustersRuntimeIDStatusRequest(server string, runtimeID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "runtimeID", runtime.ParamLocationPath, runtimeID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutClustersRuntimeIDStatusRequest calls the generic PutClustersRuntimeIDStatus builder with application/json body
func NewPutClustersRuntimeIDStatusRequest(server string, runtimeID string, body PutClustersRuntimeIDStatusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutClustersRuntimeIDStatusRequestWithBody(server, runtimeID, "application/json", bodyReader)
}

// NewPutClustersRuntimeIDStatusRequestWithBody generates requests for PutClustersRuntimeIDStatus with any type of body
func NewPutClustersRuntimeIDStatusRequestWithBody(server string, runtimeID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "runtimeID", runtime.ParamLocationPath, runtimeID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetClustersRuntimeIDStatusChangesRequest generates requests for GetClustersRuntimeIDStatusChanges
func NewGetClustersRuntimeIDStatusChangesRequest(server string, runtimeID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "runtimeID", runtime.ParamLocationPath, runtimeID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s/statusChanges", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostOperationsSchedulingIDCorrelationIDStopRequest calls the generic PostOperationsSchedulingIDCorrelationIDStop builder with application/json body
func NewPostOperationsSchedulingIDCorrelationIDStopRequest(server string, schedulingID string, correlationID string, body PostOperationsSchedulingIDCorrelationIDStopJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOperationsSchedulingIDCorrelationIDStopRequestWithBody(server, schedulingID, correlationID, "application/json", bodyReader)
}

// NewPostOperationsSchedulingIDCorrelationIDStopRequestWithBody generates requests for PostOperationsSchedulingIDCorrelationIDStop with any type of body
func NewPostOperationsSchedulingIDCorrelationIDStopRequestWithBody(server string, schedulingID string, correlationID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "schedulingID", runtime.ParamLocationPath, schedulingID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "correlationID", runtime.ParamLocationPath, correlationID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/operations/%s/%s/stop", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetReconciliationsRequest generates requests for GetReconciliations
func NewGetReconciliationsRequest(server string, params *GetReconciliationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reconciliations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.RuntimeID != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "runtimeID", runtime.ParamLocationQuery, *params.RuntimeID); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Status != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReconciliationsSchedulingIDInfoRequest generates requests for GetReconciliationsSchedulingIDInfo
func NewGetReconciliationsSchedulingIDInfoRequest(server string, schedulingID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "schedulingID", runtime.ParamLocationPath, schedulingID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reconciliations/%s/info", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostClusters request with any body
	PostClustersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostClustersResponse, error)

	PostClustersWithResponse(ctx context.Context, body PostClustersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostClustersResponse, error)

	// PutClusters request with any body
	PutClustersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutClustersResponse, error)

	PutClustersWithResponse(ctx context.Context, body PutClustersJSONRequestBody, reqEditors ...RequestEditorFn) (*PutClustersResponse, error)

	// DeleteClustersRuntimeID request
	DeleteClustersRuntimeIDWithResponse(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*DeleteClustersRuntimeIDResponse, error)

	// GetClustersRuntimeIDConfigConfigVersionStatus request
	GetClustersRuntimeIDConfigConfigVersionStatusWithResponse(ctx context.Context, runtimeID string, configVersion string, reqEditors ...RequestEditorFn) (*GetClustersRuntimeIDConfigConfigVersionStatusResponse, error)

	// GetClustersRuntimeIDStatus request
	GetClustersRuntimeIDStatusWithResponse(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*GetClustersRuntimeIDStatusResponse, error)

	// PutClustersRuntimeIDStatus request with any body
	PutClustersRuntimeIDStatusWithBodyWithResponse(ctx context.Context, runtimeID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutClustersRuntimeIDStatusResponse, error)

	PutClustersRuntimeIDStatusWithResponse(ctx context.Context, runtimeID string, body PutClustersRuntimeIDStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PutClustersRuntimeIDStatusResponse, error)

	// GetClustersRuntimeIDStatusChanges request
	GetClustersRuntimeIDStatusChangesWithResponse(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*GetClustersRuntimeIDStatusChangesResponse, error)

	// PostOperationsSchedulingIDCorrelationIDStop request with any body
	PostOperationsSchedulingIDCorrelationIDStopWithBodyWithResponse(ctx context.Context, schedulingID string, correlationID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOperationsSchedulingIDCorrelationIDStopResponse, error)

	PostOperationsSchedulingIDCorrelationIDStopWithResponse(ctx context.Context, schedulingID string, correlationID string, body PostOperationsSchedulingIDCorrelationIDStopJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOperationsSchedulingIDCorrelationIDStopResponse, error)

	// GetReconciliations request
	GetReconciliationsWithResponse(ctx context.Context, params *GetReconciliationsParams, reqEditors ...RequestEditorFn) (*GetReconciliationsResponse, error)

	// GetReconciliationsSchedulingIDInfo request
	GetReconciliationsSchedulingIDInfoWithResponse(ctx context.Context, schedulingID string, reqEditors ...RequestEditorFn) (*GetReconciliationsSchedulingIDInfoResponse, error)
}

type PostClustersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HTTPClusterResponse
	JSON400      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostClustersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostClustersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutClustersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HTTPClusterResponse
	JSON400      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutClustersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutClustersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteClustersRuntimeIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HTTPClusterResponse
	JSON400      *HTTPErrorResponse
	JSON404      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteClustersRuntimeIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteClustersRuntimeIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClustersRuntimeIDConfigConfigVersionStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HTTPClusterResponse
	JSON400      *HTTPErrorResponse
	JSON404      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetClustersRuntimeIDConfigConfigVersionStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClustersRuntimeIDConfigConfigVersionStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClustersRuntimeIDStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HTTPClusterResponse
	JSON400      *HTTPErrorResponse
	JSON404      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetClustersRuntimeIDStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClustersRuntimeIDStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutClustersRuntimeIDStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *HTTPClusterResponse
	JSON400      *HTTPErrorResponse
	JSON404      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutClustersRuntimeIDStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutClustersRuntimeIDStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClustersRuntimeIDStatusChangesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HTTPClusterStatusResponse
	JSON400      *HTTPErrorResponse
	JSON404      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetClustersRuntimeIDStatusChangesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClustersRuntimeIDStatusChangesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOperationsSchedulingIDCorrelationIDStopResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *HTTPErrorResponse
	JSON404      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostOperationsSchedulingIDCorrelationIDStopResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOperationsSchedulingIDCorrelationIDStopResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetReconciliationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HTTPReconcilerStatus
	JSON400      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetReconciliationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReconciliationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetReconciliationsSchedulingIDInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HTTPReconciliationOperations
	JSON400      *HTTPErrorResponse
	JSON500      *HTTPErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetReconciliationsSchedulingIDInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReconciliationsSchedulingIDInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostClustersWithBodyWithResponse request with arbitrary body returning *PostClustersResponse
func (c *ClientWithResponses) PostClustersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostClustersResponse, error) {
	rsp, err := c.PostClustersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostClustersResponse(rsp)
}

func (c *ClientWithResponses) PostClustersWithResponse(ctx context.Context, body PostClustersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostClustersResponse, error) {
	rsp, err := c.PostClusters(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostClustersResponse(rsp)
}

// PutClustersWithBodyWithResponse request with arbitrary body returning *PutClustersResponse
func (c *ClientWithResponses) PutClustersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutClustersResponse, error) {
	rsp, err := c.PutClustersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutClustersResponse(rsp)
}

func (c *ClientWithResponses) PutClustersWithResponse(ctx context.Context, body PutClustersJSONRequestBody, reqEditors ...RequestEditorFn) (*PutClustersResponse, error) {
	rsp, err := c.PutClusters(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutClustersResponse(rsp)
}

// DeleteClustersRuntimeIDWithResponse request returning *DeleteClustersRuntimeIDResponse
func (c *ClientWithResponses) DeleteClustersRuntimeIDWithResponse(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*DeleteClustersRuntimeIDResponse, error) {
	rsp, err := c.DeleteClustersRuntimeID(ctx, runtimeID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteClustersRuntimeIDResponse(rsp)
}

// GetClustersRuntimeIDConfigConfigVersionStatusWithResponse request returning *GetClustersRuntimeIDConfigConfigVersionStatusResponse
func (c *ClientWithResponses) GetClustersRuntimeIDConfigConfigVersionStatusWithResponse(ctx context.Context, runtimeID string, configVersion string, reqEditors ...RequestEditorFn) (*GetClustersRuntimeIDConfigConfigVersionStatusResponse, error) {
	rsp, err := c.GetClustersRuntimeIDConfigConfigVersionStatus(ctx, runtimeID, configVersion, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClustersRuntimeIDConfigConfigVersionStatusResponse(rsp)
}

// GetClustersRuntimeIDStatusWithResponse request returning *GetClustersRuntimeIDStatusResponse
func (c *ClientWithResponses) GetClustersRuntimeIDStatusWithResponse(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*GetClustersRuntimeIDStatusResponse, error) {
	rsp, err := c.GetClustersRuntimeIDStatus(ctx, runtimeID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClustersRuntimeIDStatusResponse(rsp)
}

// PutClustersRuntimeIDStatusWithBodyWithResponse request with arbitrary body returning *PutClustersRuntimeIDStatusResponse
func (c *ClientWithResponses) PutClustersRuntimeIDStatusWithBodyWithResponse(ctx context.Context, runtimeID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutClustersRuntimeIDStatusResponse, error) {
	rsp, err := c.PutClustersRuntimeIDStatusWithBody(ctx, runtimeID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutClustersRuntimeIDStatusResponse(rsp)
}

func (c *ClientWithResponses) PutClustersRuntimeIDStatusWithResponse(ctx context.Context, runtimeID string, body PutClustersRuntimeIDStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PutClustersRuntimeIDStatusResponse, error) {
	rsp, err := c.PutClustersRuntimeIDStatus(ctx, runtimeID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutClustersRuntimeIDStatusResponse(rsp)
}

// GetClustersRuntimeIDStatusChangesWithResponse request returning *GetClustersRuntimeIDStatusChangesResponse
func (c *ClientWithResponses) GetClustersRuntimeIDStatusChangesWithResponse(ctx context.Context, runtimeID string, reqEditors ...RequestEditorFn) (*GetClustersRuntimeIDStatusChangesResponse, error) {
	rsp, err := c.GetClustersRuntimeIDStatusChanges(ctx, runtimeID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClustersRuntimeIDStatusChangesResponse(rsp)
}

// PostOperationsSchedulingIDCorrelationIDStopWithBodyWithResponse request with arbitrary body returning *PostOperationsSchedulingIDCorrelationIDStopResponse
func (c *ClientWithResponses) PostOperationsSchedulingIDCorrelationIDStopWithBodyWithResponse(ctx context.Context, schedulingID string, correlationID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOperationsSchedulingIDCorrelationIDStopResponse, error) {
	rsp, err := c.PostOperationsSchedulingIDCorrelationIDStopWithBody(ctx, schedulingID, correlationID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOperationsSchedulingIDCorrelationIDStopResponse(rsp)
}

func (c *ClientWithResponses) PostOperationsSchedulingIDCorrelationIDStopWithResponse(ctx context.Context, schedulingID string, correlationID string, body PostOperationsSchedulingIDCorrelationIDStopJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOperationsSchedulingIDCorrelationIDStopResponse, error) {
	rsp, err := c.PostOperationsSchedulingIDCorrelationIDStop(ctx, schedulingID, correlationID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOperationsSchedulingIDCorrelationIDStopResponse(rsp)
}

// GetReconciliationsWithResponse request returning *GetReconciliationsResponse
func (c *ClientWithResponses) GetReconciliationsWithResponse(ctx context.Context, params *GetReconciliationsParams, reqEditors ...RequestEditorFn) (*GetReconciliationsResponse, error) {
	rsp, err := c.GetReconciliations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReconciliationsResponse(rsp)
}

// GetReconciliationsSchedulingIDInfoWithResponse request returning *GetReconciliationsSchedulingIDInfoResponse
func (c *ClientWithResponses) GetReconciliationsSchedulingIDInfoWithResponse(ctx context.Context, schedulingID string, reqEditors ...RequestEditorFn) (*GetReconciliationsSchedulingIDInfoResponse, error) {
	rsp, err := c.GetReconciliationsSchedulingIDInfo(ctx, schedulingID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReconciliationsSchedulingIDInfoResponse(rsp)
}

// ParsePostClustersResponse parses an HTTP response from a PostClustersWithResponse call
func ParsePostClustersResponse(rsp *http.Response) (*PostClustersResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PostClustersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HTTPClusterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutClustersResponse parses an HTTP response from a PutClustersWithResponse call
func ParsePutClustersResponse(rsp *http.Response) (*PutClustersResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PutClustersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HTTPClusterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteClustersRuntimeIDResponse parses an HTTP response from a DeleteClustersRuntimeIDWithResponse call
func ParseDeleteClustersRuntimeIDResponse(rsp *http.Response) (*DeleteClustersRuntimeIDResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &DeleteClustersRuntimeIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HTTPClusterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetClustersRuntimeIDConfigConfigVersionStatusResponse parses an HTTP response from a GetClustersRuntimeIDConfigConfigVersionStatusWithResponse call
func ParseGetClustersRuntimeIDConfigConfigVersionStatusResponse(rsp *http.Response) (*GetClustersRuntimeIDConfigConfigVersionStatusResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetClustersRuntimeIDConfigConfigVersionStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HTTPClusterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetClustersRuntimeIDStatusResponse parses an HTTP response from a GetClustersRuntimeIDStatusWithResponse call
func ParseGetClustersRuntimeIDStatusResponse(rsp *http.Response) (*GetClustersRuntimeIDStatusResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetClustersRuntimeIDStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HTTPClusterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutClustersRuntimeIDStatusResponse parses an HTTP response from a PutClustersRuntimeIDStatusWithResponse call
func ParsePutClustersRuntimeIDStatusResponse(rsp *http.Response) (*PutClustersRuntimeIDStatusResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PutClustersRuntimeIDStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest HTTPClusterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetClustersRuntimeIDStatusChangesResponse parses an HTTP response from a GetClustersRuntimeIDStatusChangesWithResponse call
func ParseGetClustersRuntimeIDStatusChangesResponse(rsp *http.Response) (*GetClustersRuntimeIDStatusChangesResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetClustersRuntimeIDStatusChangesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HTTPClusterStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostOperationsSchedulingIDCorrelationIDStopResponse parses an HTTP response from a PostOperationsSchedulingIDCorrelationIDStopWithResponse call
func ParsePostOperationsSchedulingIDCorrelationIDStopResponse(rsp *http.Response) (*PostOperationsSchedulingIDCorrelationIDStopResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PostOperationsSchedulingIDCorrelationIDStopResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetReconciliationsResponse parses an HTTP response from a GetReconciliationsWithResponse call
func ParseGetReconciliationsResponse(rsp *http.Response) (*GetReconciliationsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetReconciliationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HTTPReconcilerStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetReconciliationsSchedulingIDInfoResponse parses an HTTP response from a GetReconciliationsSchedulingIDInfoWithResponse call
func ParseGetReconciliationsSchedulingIDInfoResponse(rsp *http.Response) (*GetReconciliationsSchedulingIDInfoResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetReconciliationsSchedulingIDInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HTTPReconciliationOperations
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
