apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configurationConfigMap }}
  namespace: {{ .Release.Namespace }}
data:
  component-reconcilers.json: |-
    {
    {{- include "mothership-reconciler.component-reconcilers" . | trimAll "," | nindent 6 }}
    }
---
