apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configurationSecret }}
  namespace: {{ .Release.Namespace }}
data:
  postgresql-sslRootCert: {{ .Values.global.database.managedGCP.sslRootCert | quote }}
  reconciler.yaml: |-
    {{ tpl (.Files.Get "files/reconciler.yaml") . | b64enc }}
---
