apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: mothership-api
spec:
  match:
    methods: ["GET", "PUT", "DELETE"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></oauth/([^/]+/)?v2/.*>
  authenticators:
  - handler: oauth2_introspection
    config:
      required_scope: ["broker:write"]
  authorizer:
    handler: allow
  upstream:
    url: http://{{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: mothership-reconciles
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.operator }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods: ["GET"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></reconciles.*>
  upstream:
    url: http://{{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: mothership-clusters
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.operator }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods: ["PUT", "POST"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></clusters.*>
  upstream:
    url: http://{{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: mothership-clusters-runtimeid
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.operator }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods: ["DELETE"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></clusters/.+>
  upstream:
    url: http://{{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: mothership-clusters-runtimeid-status
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.operator }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods: ["PUT", "GET"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></clusters/.+/status.*>
  upstream:
    url: http://{{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: mothership-clusters-runtimeid-config-version-status
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.operator }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods: ["PUT"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></clusters/.+/config/.+/status.*>
  upstream:
    url: http://{{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: mothership-clusters-runtimeid-statuschanges
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.operator }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods: ["GET"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></clusters/.+/statusChanges.*>
  upstream:
    url: http://{{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
