apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.mothership_reconciler.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml .Values.serviceAccount.annotations) . | indent 4 }}
{{- end }}