{{- if and .Values.global.mothership_reconciler.expose (.Capabilities.APIVersions.Has "networking.istio.io/v1beta1") }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  gateways:
    - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
    {{- if .Values.global.istio.additionalGateways }}
    {{ toYaml .Values.global.istio.additionalGateways | nindent 4 }}
    {{- end }}
  hosts:
  - {{ .Values.host }}.{{ .Values.global.ingress.domainName }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: "/v.+/reconciliations.*"
    route:
    - destination:
        host: {{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["PUT", "POST", "GET", "DELETE"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: "/v.+/clusters.*"
    route:
    - destination:
        host: {{ include "mothership-reconciler.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
{{- end }}
