apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  gateways:
  - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
  hosts:
  - {{ .Values.host }}.{{ .Values.global.ingress.domainName }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - X-Broker-API-Version
      allowMethods: ["GET", "PUT", "DELETE"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /oauth/([^/]+/)?v2/.*
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
      regex: "/reconciles.*"
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["PUT", "POST"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
      regex: "/clusters.*"
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["DELETE"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
      regex: "/clusters/.+"
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["PUT", "GET"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
      regex: "/clusters/.+/status.*"
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
      regex: "/clusters/.+/config/.+/status.*"
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
      regex: "/clusters/.+/statusChanges.*"
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
    