apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  gateways:
  - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
  hosts:
  - {{ .Values.host }}.{{ .Values.global.ingress.domainName }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: "/v.+/reconciles.*"
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["PUT", "POST", "GET", "DELETE"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: "/v.+/clusters.*"
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
