// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GardenerClient is an autogenerated mock type for the GardenerClient type
type GardenerClient struct {
	mock.Mock
}

// List provides a mock function with given fields: _a0, opts
func (_m *GardenerClient) List(_a0 context.Context, opts v1.ListOptions) (*unstructured.UnstructuredList, error) {
	ret := _m.Called(_a0, opts)

	var r0 *unstructured.UnstructuredList
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *unstructured.UnstructuredList); ok {
		r0 = rf(_a0, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.UnstructuredList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(_a0, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGardenerClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewGardenerClient creates a new instance of GardenerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGardenerClient(t mockConstructorTestingTNewGardenerClient) *GardenerClient {
	mock := &GardenerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
