// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/control-plane/components/provisioner/internal/apperrors"
	gqlschema "github.com/kyma-project/control-plane/components/provisioner/pkg/gqlschema"

	mock "github.com/stretchr/testify/mock"
)

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// ValidateProvisioningInput provides a mock function with given fields: input
func (_m *Validator) ValidateProvisioningInput(input gqlschema.ProvisionRuntimeInput) apperrors.AppError {
	ret := _m.Called(input)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(gqlschema.ProvisionRuntimeInput) apperrors.AppError); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// ValidateUpgradeShootInput provides a mock function with given fields: input
func (_m *Validator) ValidateUpgradeShootInput(input gqlschema.UpgradeShootInput) apperrors.AppError {
	ret := _m.Called(input)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(gqlschema.UpgradeShootInput) apperrors.AppError); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
