// Code generated by mockery v2.6.0. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"
)

// DeprovisionerStorage is an autogenerated mock type for the DeprovisionerStorage type
type DeprovisionerStorage struct {
	mock.Mock
}

// RemoveInstance provides a mock function with given fields: instance
func (_m *DeprovisionerStorage) RemoveInstance(instance internal.CLSInstance) error {
	ret := _m.Called(instance)

	var r0 error
	if rf, ok := ret.Get(0).(func(internal.CLSInstance) error); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveReference provides a mock function with given fields: globalAccountID, skrInstanceID
func (_m *DeprovisionerStorage) RemoveReference(globalAccountID string, skrInstanceID string) error {
	ret := _m.Called(globalAccountID, skrInstanceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(globalAccountID, skrInstanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
