// Code generated by mockery v2.6.0. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"
)

// InstanceStorage is an autogenerated mock type for the InstanceStorage type
type InstanceStorage struct {
	mock.Mock
}

// AddReference provides a mock function with given fields: globalAccountID, subAccountID
func (_m *InstanceStorage) AddReference(globalAccountID string, subAccountID string) error {
	ret := _m.Called(globalAccountID, subAccountID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(globalAccountID, subAccountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindInstance provides a mock function with given fields: globalAccountID
func (_m *InstanceStorage) FindInstance(globalAccountID string) (*internal.CLSInstance, bool, error) {
	ret := _m.Called(globalAccountID)

	var r0 *internal.CLSInstance
	if rf, ok := ret.Get(0).(func(string) *internal.CLSInstance); ok {
		r0 = rf(globalAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.CLSInstance)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(globalAccountID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(globalAccountID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InsertInstance provides a mock function with given fields: instance
func (_m *InstanceStorage) InsertInstance(instance internal.CLSInstance) error {
	ret := _m.Called(instance)

	var r0 error
	if rf, ok := ret.Get(0).(func(internal.CLSInstance) error); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
