// Code generated by mockery v2.6.0. DO NOT EDIT.

package automock

import (
	servicemanager "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/servicemanager"
	mock "github.com/stretchr/testify/mock"
)

// InstanceCreator is an autogenerated mock type for the InstanceCreator type
type InstanceCreator struct {
	mock.Mock
}

// CreateInstance provides a mock function with given fields: smClient, brokerID, serviceID, planID, instanceID
func (_m *InstanceCreator) CreateInstance(smClient servicemanager.Client, brokerID string, serviceID string, planID string, instanceID string) error {
	ret := _m.Called(smClient, brokerID, serviceID, planID, instanceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(servicemanager.Client, string, string, string, string) error); ok {
		r0 = rf(smClient, brokerID, serviceID, planID, instanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
