// Code generated by mockery v2.6.0. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"
)

// ProvisionerStorage is an autogenerated mock type for the ProvisionerStorage type
type ProvisionerStorage struct {
	mock.Mock
}

// FindActiveByGlobalAccountID provides a mock function with given fields: globalAccountID
func (_m *ProvisionerStorage) FindActiveByGlobalAccountID(globalAccountID string) (*internal.CLSInstance, bool, error) {
	ret := _m.Called(globalAccountID)

	var r0 *internal.CLSInstance
	if rf, ok := ret.Get(0).(func(string) *internal.CLSInstance); ok {
		r0 = rf(globalAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.CLSInstance)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(globalAccountID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(globalAccountID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Insert provides a mock function with given fields: instance
func (_m *ProvisionerStorage) Insert(instance internal.CLSInstance) error {
	ret := _m.Called(instance)

	var r0 error
	if rf, ok := ret.Get(0).(func(internal.CLSInstance) error); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reference provides a mock function with given fields: version, clsInstanceID, skrInstanceID
func (_m *ProvisionerStorage) Reference(version int, clsInstanceID string, skrInstanceID string) error {
	ret := _m.Called(version, clsInstanceID, skrInstanceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = rf(version, clsInstanceID, skrInstanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
