// Code generated by mockery v2.6.0. DO NOT EDIT.

package automock

import (
	cls "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/cls"
	mock "github.com/stretchr/testify/mock"

	servicemanager "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/servicemanager"
)

// StatusChecker is an autogenerated mock type for the StatusChecker type
type StatusChecker struct {
	mock.Mock
}

// CheckStatus provides a mock function with given fields: smClient, instanceKey
func (_m *StatusChecker) CheckStatus(smClient servicemanager.Client, instanceKey servicemanager.InstanceKey) (cls.ProvisionStatus, error) {
	ret := _m.Called(smClient, instanceKey)

	var r0 cls.ProvisionStatus
	if rf, ok := ret.Get(0).(func(servicemanager.Client, servicemanager.InstanceKey) cls.ProvisionStatus); ok {
		r0 = rf(smClient, instanceKey)
	} else {
		r0 = ret.Get(0).(cls.ProvisionStatus)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(servicemanager.Client, servicemanager.InstanceKey) error); ok {
		r1 = rf(smClient, instanceKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
