// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	notification "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/notification"
	mock "github.com/stretchr/testify/mock"
)

// BundleBuilder is an autogenerated mock type for the BundleBuilder type
type BundleBuilder struct {
	mock.Mock
}

// DisabledCheck provides a mock function with given fields:
func (_m *BundleBuilder) DisabledCheck() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewBundle provides a mock function with given fields: identifier, notificationParams
func (_m *BundleBuilder) NewBundle(identifier string, notificationParams notification.NotificationParams) (notification.Bundle, error) {
	ret := _m.Called(identifier, notificationParams)

	var r0 notification.Bundle
	if rf, ok := ret.Get(0).(func(string, notification.NotificationParams) notification.Bundle); ok {
		r0 = rf(identifier, notificationParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.Bundle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, notification.NotificationParams) error); ok {
		r1 = rf(identifier, notificationParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
