{
 "title": "Reconciler",
 "tags": [ "reconciler" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Logging (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"logging\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"logging\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"logging\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"logging\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"logging\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Monitoring (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"monitoring\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"monitoring\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"monitoring\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"monitoring\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"monitoring\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "API Gateway (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"api-gateway\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"api-gateway\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"api-gateway\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"api-gateway\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"api-gateway\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Service Catalog (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"service-catalog\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"service-catalog\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"service-catalog\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"service-catalog\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"service-catalog\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Service Catalog Addons (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"service-catalog-addons\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"service-catalog-addons\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"service-catalog-addons\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"service-catalog-addons\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"service-catalog-addons\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Helm Broker (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"helm-broker\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"helm-broker\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"helm-broker\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"helm-broker\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"helm-broker\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Cluster Users (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"cluster-users\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"cluster-users\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"cluster-users\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"cluster-users\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"cluster-users\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Application Connector (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"application-connector\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"application-connector\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"application-connector\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"application-connector\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"application-connector\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "CRDs (Base)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (reconciler_processing_time_bucket{component=\"CRDs\",metric=\"processing_duration_successful_millisecond\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"CRDs\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"CRDs\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"CRDs\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"CRDs\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Serverless", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reconciler_processing_time_bucket{component=\"serverless\",metric=\"processing_duration_successful_millisecond\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"serverless\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"serverless\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"serverless\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"serverless\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Rafter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reconciler_processing_time_bucket{component=\"rafter\",metric=\"processing_duration_successful_millisecond\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"rafter\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"rafter\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"rafter\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"rafter\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Ory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reconciler_processing_time_bucket{component=\"ory\",metric=\"processing_duration_successful_millisecond\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"ory\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"ory\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"ory\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"ory\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Eventing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reconciler_processing_time_bucket{component=\"eventing\",metric=\"processing_duration_successful_millisecond\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"eventing\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"eventing\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"eventing\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"eventing\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Cluster Essentials", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reconciler_processing_time_bucket{component=\"cluster-essentials\",metric=\"processing_duration_successful_millisecond\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"cluster-essentials\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"cluster-essentials\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"cluster-essentials\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"cluster-essentials\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Istio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 } },
  {
   "title": "Successful Processing Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reconciler_processing_time_bucket{component=\"istio\",metric=\"processing_duration_successful_millisecond\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reconciler_processing_time_count{component=\"istio\",metric=\"processing_duration_unsuccessful_millisecond\"}) /sum(reconciler_processing_time_count{component=\"istio\",metric=\"processing_duration_unsuccessful_millisecond\"} + ignoring(metric) reconciler_processing_time_count{component=\"istio\",metric=\"processing_duration_successful_millisecond\"})"
    }
   ]
  },
  {
   "title": "Successful Processing Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(reconciler_processing_time_bucket{component=\"istio\",metric=\"processing_duration_successful_millisecond\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Mothership", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 226 } },
  {
   "title": "Cluster Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 227 },
   "targets": [
    {
     "expr": "(count(reconciler_reconciliation_status{}==0))",
     "legendFormat": "Reconcile Error"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==1))",
     "legendFormat": "Ready"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==2))",
     "legendFormat": "Reconcile Pending"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==3))",
     "legendFormat": "Reconciling"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==4))",
     "legendFormat": "Reconcile Disabled"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==5))",
     "legendFormat": "Delete Pending"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==6))",
     "legendFormat": "Deleting"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==7))",
     "legendFormat": "Delete Error"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==8))",
     "legendFormat": "Deleted"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==9))",
     "legendFormat": "Reconcile Error Retryable"
    },
    {
     "expr": "(count(reconciler_reconciliation_status{}==10))",
     "legendFormat": "Delete Error Retryable"
    }
   ]
  },
  {
   "title": "Mothership - Workers Occupancy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 227 },
   "targets": [
    {
     "expr": "reconciler_worker_pool_occupancy_ratio{component=\"mothership\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Waiting Reconciliations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reconciler_reconciliation_waiting_total{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total number of clusters currently reconciling or in error/failed state",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 235 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reconciler_reconciliation_not_ready_total{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 } },
  {
   "title": "Reconciler Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\", namespace=\"reconciler\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Reconciler CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 251 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"reconciler\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 258 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\", cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=\"$cluster\"}) by (namespace)"
      }
     ]
    }
   ]
  },
  { "title": "Memory Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 259 } },
  {
   "title": "Requests by Namespace",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 260 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\", cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  { "title": "Current Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 267 } },
  {
   "title": "Current Network Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 268 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    }
   ]
  },
  { "title": "Rate of Packets Dropped", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 276 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}