{{ if .Values.global.component_reconcilers.authentication }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: rma-reconciler
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      kyma-project.io/component-reconciler: ""
      component: rma
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.global.mothership_reconciler.serviceAccountName }}"]
{{- end }}
