apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kyma-project.io/component-reconciler: ""
    component: rma
  name: rma-reconciler
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      kyma-project.io/component-reconciler: ""
      component: rma
  replicas: 1
  template:
    metadata:
      labels:
        kyma-project.io/component-reconciler: ""
        component: rma
    spec:
      serviceAccountName: component-reconcilers-rma
      containers:
      - image: "{{ .Values.global.images.component_reconciler }}"
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        args:
          - reconciler
          - start
          - rma
          - --workspace=/tmp/reconciler
          - --verbose
          - --worker-count={{ .Values.config.workerCount }}
          - --worker-timeout={{ .Values.config.workerTimeout }}
          - --retries-max={{ .Values.config.retriesMax }}
          - --retries-delay={{ .Values.config.retriesDelay }}
        name: reconciler
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources: {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp
          name: workspace
      securityContext:
        runAsUser: 2000
      volumes:
      - emptyDir: {}
        name: workspace
