apiVersion: v1
kind: ServiceAccount
metadata:
  name: component-reconcilers-rma
  namespace:  {{ .Release.Namespace }}
  labels:
    app: component-reconcilers-rma
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: component-reconcilers-rma
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: ["operator.victoriametrics.com"]
    resources: ["vmrules"]
    verbs: ["*"]
  - apiGroups: ["operator.victoriametrics.com"]
    resources: ["vmusers"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: component-reconcilers-rma
subjects:
  - kind: ServiceAccount
    name: component-reconcilers-rma
    namespace:  {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: component-reconcilers-rma
