[[constraint]]
  name = "code.cloudfoundry.org/lager"
  version = "2.0.0"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.22.0"

[[constraint]]
  name = "github.com/gocraft/dbr"
  version = "2.6.1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.2"

[[constraint]]
  name = "github.com/kyma-incubator/compass"
  revision = "baf11bc035cbfd893baf6b0ad2a5ca7483bf12c9"

[[constraint]]
  name = "github.com/kyma-project/control-plane"
  revision = "dbd90902ce293f594793d54020287c138859f2eb"

[[constraint]]
  name = "github.com/kyma-project/kyma"
  version = "1.11.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.3.0"

[[constraint]]
  name = "github.com/machinebox/graphql"
  version = "0.2.2"

[[constraint]]
  name = "github.com/pivotal-cf/brokerapi"
  revision = "e10bf387f6d5a91e9e7b02b76ee8d2748d7d6f60"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.9.1"

[[override]]
  name = "github.com/sirupsen/logrus"
  version = "1.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "github.com/testcontainers/testcontainers-go"
  version = "v0.10.0"

[[constraint]]
  name = "github.com/vrischmann/envconfig"
  version = "1.2.0"

[[constraint]]
  name = "github.com/Peripli/service-manager"
  version = "v0.18.9"

[[constraint]]
  name = "github.com/Peripli/service-manager-cli"
  version = "v1.11.6"

# Azure
[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v47.1.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "autorest/v0.11.10"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.8"

[[override]]
  name = "github.com/tidwall/gjson"
  version = "v1.6.8"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "75cca531ea763666bc46e531da3b4c3b95f64557"

[[override]]
  name = "github.com/tidwall/match"
  version = "v1.0.3"

[[override]]
  name = "golang.org/x/text"
  version = "v0.3.5"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "v1.3.2"

[[override]]
name = "github.com/docker/docker"
version = "v20.10.5"

[[override]]
name = "github.com/Microsoft/hcsshim"
version = "v0.8.15"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
