dependencies:
- name: postgresql
  condition: global.database.embedded.enabled
- name: provisioner
  condition: global.provisioning.enabled
- name: kyma-environment-broker
  condition: global.kyma_environment_broker.enabled
- name: kyma-metrics-collector
  condition: global.kyma_metrics_collector.enabled
- name: mothership-reconciler
  condition: global.mothership_reconciler.enabled
- name: component-reconcilers
  condition: global.component_reconcilers.enabled