groups:
  - name: kmc.rules
    rules:
    - alert: KMCDown
      expr: up{job="kcp-kyma-metrics-collector", namespace="kcp-system"} == 0
      for: 10m
      labels:
        severity: critical
      annotations:
        description: KMC has disappeared from Prometheus target discovery.
  - name: kmc.rules.edp
    rules:
    - alert: EDPRequestFailures
      expr: rate(kmc_edp_request_duration_seconds_count{status!~"2.."}[10m]) > 0
      for: 10m
      labels:
        severity: critical
      annotations:
        description: Increase in failed requests from KMC to EDP.
    - alert: EDPRequestDuration
      # if for the 95 percentile, the latency (in milliseconds) is greater than 500ms.
      expr: histogram_quantile(0.95, sum by (le) (rate(kmc_edp_request_duration_seconds_bucket[10m]))) * 1000 > 500
      for: 10m
      labels:
        severity: warning
      annotations:
        description: Average request duration from KMC to EDP.
  - name: kmc.rules.keb
    rules:
    - alert: KEBRequestFailures
      # Requests to KEB are done every 10 minutes.
      expr: rate(kmc_keb_request_duration_seconds_count{status!~"2.."}[40m]) > 0
      for: 10m
      labels:
        severity: critical
      annotations:
        description: Increase in failed requests from KMC to KEB.
    - alert: KEBRequestDuration
      expr: histogram_quantile(0.95, sum by (le) (rate(kmc_keb_request_duration_seconds_bucket[40m]))) * 1000 > 800
      for: 20m
      labels:
        severity: warning
      annotations:
        description: Average request duration from KMC to KEB.
  - name: kmc.rules.skr
    rules:
    - alert: SKRErrors
      expr: sum by (sub_account_id) (rate(kmc_skr_query_total{success="true"}[30m])) / sum by (sub_account_id) (rate(kmc_skr_query_total{}[30m])) * 100  < 90
      for: 10m
      labels:
        severity: critical
      annotations:
        description: "Success rate of KMC in listing PVCs, SVCs and Nodes for SKR in subaccount: {{ $labels.sub_account_id }}"
  - name: kmc.rules.processing
    rules:
    - alert: KMCProcessingNewUpdateWarning
      expr: time() - kmc_process_sub_account_processed_timestamp_seconds{with_old_metric="false"} >= 900
      labels:
        severity: warning
      annotations:
        summary: "Sending new data to EDP failed"
        description: "Could not send new usage data for {{ $labels.sub_account_id }} to EDP. Last successful send {{ $value }} seconds ago"
    - alert: KMCProcessingNewUpdate
      # it will alert when the subAccount is not processed with new data for some time.
      expr: time() - kmc_process_sub_account_processed_timestamp_seconds{with_old_metric="false"} >= 3600
      labels:
        severity: critical
      annotations:
        summary: "Sending new data to EDP failed"
        description: "Could not send new usage data for {{ $labels.sub_account_id }} to EDP. Last successful send {{ $value }} seconds ago"

    - alert: KMCProcessingFailed
      # it will alert when the subAccount is not being able to processed at all and no data is published to EDP.
      expr: rate(kmc_process_sub_account_total{success="false"}[15m]) > 0
      for: 60m
      labels:
        severity: critical
      annotations:
        summary: "Processing sub-account failed"
        description: "Could not process subAccount {{ $labels.sub_account_id }}"
    - alert: KMCNumberOfClustersFromKEBDropped
      # it will alert when the amount of trackable fetched clusters from KEB drops below 40% of the average of the last 20 minutes.
      # the sub-query sum() in the query avg_over_time() is calculated with step=4m in the scrape_interval=20m
      expr: (sum(kmc_process_fetched_clusters{trackable="true"})) / (avg_over_time(sum(kmc_process_fetched_clusters{trackable="true"})[20m:4m])) < 0.9
      for: 5m
      labels:
        severity: critical
      annotations:
        description: Fetching clusters obtained from KEB failed.
    - alert: KMCFetchingClustersFromKEBReturnsNoData
      # fetching clusters from KMC happens every 10min
      # it will alert when the last 2 requests to KMC returned no data.
      expr: absent_over_time(kmc_process_fetched_clusters[20m])
      labels:
        severity: critical
      annotations:
        description: No data obtained from KEB.
