{{- if eq .Values.gardener.manageSecrets true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gardener.secretName }}
  namespace: {{ .Release.Namespace }}
  {{- if and .Values.helmAnnotation or .Values.argoAnnotation }}
  annotations:
    {{- if .Values.helmAnnotation }}
    "helm.sh/resource-policy": {{ .Values.gardener.resourcePolicy }}
    {{- end }}
    {{- if .Values.argoAnnotation }}
    "argocd.argoproj.io/hook": {{ .Values.gardener.kubeconfigResourceHook }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  kubeconfig: {{ .Values.gardener.kubeconfig | quote }}
{{- end }}
