apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ template "fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  portLevelMtls:
    {{ .Values.metrics.port }}:
      mode: "PERMISSIVE"
