apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  mtls:
    mode: PERMISSIVE
