{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1beta1" }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  hosts:
    - provisioner.{{ .Values.global.ingress.domainName }}
  gateways:
    - {{ .Values.global.istio.gateway | required "Please specify .global.istio.gateway"}}
    {{- if .Values.global.istio.additionalGateways }}
    {{ toYaml .Values.global.istio.additionalGateways | nindent 4 }}
    {{- end }}
  http:
      - match:
        - uri:
            exact: /healthz
        route:
          - destination:
              port:
                number: {{ .Values.global.provisioner.graphql.port }}
              host: {{ template "fullname" . }}
{{- end }}
