// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kyma-project/control-plane/components/mothership/pkg (interfaces: URLProvider)

// Package automock is a generated GoMock package.
package automock

import (
	url "net/url"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLProvider is a mock of URLProvider interface.
type MockURLProvider struct {
	ctrl     *gomock.Controller
	recorder *MockURLProviderMockRecorder
}

// MockURLProviderMockRecorder is the mock recorder for MockURLProvider.
type MockURLProviderMockRecorder struct {
	mock *MockURLProvider
}

// NewMockURLProvider creates a new mock instance.
func NewMockURLProvider(ctrl *gomock.Controller) *MockURLProvider {
	mock := &MockURLProvider{ctrl: ctrl}
	mock.recorder = &MockURLProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLProvider) EXPECT() *MockURLProviderMockRecorder {
	return m.recorder
}

// Provide mocks base method.
func (m *MockURLProvider) Provide(arg0 string, arg1 map[string]string) url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provide", arg0, arg1)
	ret0, _ := ret[0].(url.URL)
	return ret0
}

// Provide indicates an expected call of Provide.
func (mr *MockURLProviderMockRecorder) Provide(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provide", reflect.TypeOf((*MockURLProvider)(nil).Provide), arg0, arg1)
}
