// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package cls

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	_ = packr.PackJSONBytes("./templates", "cls_override.yaml", "\"W09VVFBVVF0KICBOYW1lICAgICAgICAgICAgICBodHRwCiAgTWF0Y2ggICAgICAgICAgICAgKgogIEhvc3QgICAgICAgICAgICAgIHt7LkZsdWVudGRFbmRQb2ludH19CiAgUG9ydCAgICAgICAgICAgICAgNDQzCiAgSFRUUF9Vc2VyICAgICAgICAge3suRmx1ZW50ZFVzZXJuYW1lfX0KICBIVFRQX1Bhc3N3ZCAgICAgICB7ey5GbHVlbnRkUGFzc3dvcmR9fQogIHRscyAgICAgICAgICAgICAgIHRydWUKICB0bHMudmVyaWZ5ICAgICAgICB0cnVlCiAgdGxzLmRlYnVnICAgICAgICAgMQogIFVSSSAgICAgICAgICAgICAgIC8KICBGb3JtYXQgICAgICAgICAgICBqc29u\"")
}
