apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  config.yaml: |-
    runtimes:
      - id: "1"
        data:
          foo: bar
      - id: "2"
        data:
          bar: baz
