{{ if .Values.global.component_reconcilers.authentication }}
{{ $global := . }}
{{- range $component := .Values.global.components }}
{{ if not (hasKey $global.Subcharts $component) }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $component }}-reconciler
  namespace: {{ $global.Release.Namespace }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      kyma-project.io/component-reconciler: ""
      component: {{ $component }}
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ $global.Release.Namespace }}/sa/{{ $global.Values.global.mothership_reconciler.serviceAccountName }}"]
---
{{- end }}
{{- end }}
{{- end }}
