// Code generated by mockery v2.14.0. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"

	predicate "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/storage/predicate"
)

// InstanceFinder is an autogenerated mock type for the InstanceFinder type
type InstanceFinder struct {
	mock.Mock
}

// FindAllJoinedWithOperations provides a mock function with given fields: prct
func (_m *InstanceFinder) FindAllJoinedWithOperations(prct ...predicate.Predicate) ([]internal.InstanceWithOperation, error) {
	_va := make([]interface{}, len(prct))
	for _i := range prct {
		_va[_i] = prct[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []internal.InstanceWithOperation
	if rf, ok := ret.Get(0).(func(...predicate.Predicate) []internal.InstanceWithOperation); ok {
		r0 = rf(prct...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.InstanceWithOperation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...predicate.Predicate) error); ok {
		r1 = rf(prct...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInstanceFinder interface {
	mock.TestingT
	Cleanup(func())
}

// NewInstanceFinder creates a new instance of InstanceFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInstanceFinder(t mockConstructorTestingTNewInstanceFinder) *InstanceFinder {
	mock := &InstanceFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
