{
 "title": "Metris",
 "tags": [
  "metering",
  "metris"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "query": "label_values(metris_info,namespace)"
   },
   { "name": "job", "query": "label_values(metris_info,job)" },
   {
    "name": "provider",
    "query": "label_values(metris_azure_request_total,provider)"
   },
   {
    "name": "resource",
    "query": "label_values(metris_azure_request_total{provider=~\"$provider\"},resource)"
   },
   {
    "name": "workqueue",
    "query": "label_values(metris_workqueue_items_total,queue_name)"
   }
  ]
 },
 "panels": [
  { "title": "Azure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of requests per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(metris_azure_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\", provider=~\"$provider\", resource=~\"$resource\"}[$interval])",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (provider, resource)\n(\n  metris_azure_request_duration_seconds_sum{namespace=\"$namespace\", job=\"$job\", provider=~\"$provider\", resource=~\"$resource\"}\n  /\n  metris_azure_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\", provider=~\"$provider\", resource=~\"$resource\"}\n) * 1000",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metris_azure_request_total{namespace=\"$namespace\", job=\"$job\", provider=~\"$provider\", resource=~\"$resource\", status=~\"2..\"}[$interval])",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Requests Failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metris_azure_request_total{namespace=\"$namespace\", job=\"$job\", provider=~\"$provider\", resource=~\"$resource\", status=~\"(3|4|5)..\"}[$interval])",
     "legendFormat": "{{resource}} ({{status}})"
    }
   ]
  },
  { "title": "EDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (provider, resource)\n(\n  metris_edp_request_duration_seconds_sum{namespace=\"$namespace\", job=\"$job\"}\n  /\n  metris_edp_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\"}\n) * 1000"
    }
   ]
  },
  {
   "title": "Requests Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(metris_edp_request_total{namespace=\"$namespace\", job=\"$job\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Gardener", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Sync Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metris_gardener_error_total{namespace=\"$namespace\", job=\"$job\"}[$interval])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Workqueue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue depth",
     "type": "graph",
     "description": "Current depth of the work queue.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "clamp_min(metris_workqueue_depth{queue_name=~\"$workqueue\"},0)",
       "legendFormat": "{{queue_name}}"
      }
     ]
    },
    {
     "title": "Workqueue items rate",
     "type": "graph",
     "description": "Total number of items added to the work queue.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(metris_workqueue_items_total{queue_name=~\"$workqueue\"}[$interval])",
       "legendFormat": "{{queue_name}}"
      }
     ]
    },
    {
     "title": "Workqueue average items duration",
     "type": "graph",
     "description": "How long an item stays in the work queue.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(metris_workqueue_latency_seconds_sum{queue_name=~\"$workqueue\"}[$interval]) / rate(metris_workqueue_latency_seconds_count{queue_name=~\"$workqueue\"}[$interval])) by(queue_name)  ",
       "legendFormat": "{{queue_name}}"
      }
     ]
    },
    {
     "title": "Workqueue average work duration",
     "type": "graph",
     "description": "How long processing an item from the work queue takes.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(metris_workqueue_work_duration_seconds_sum{queue_name=~\"$workqueue\"}[$interval]) / rate(metris_workqueue_work_duration_seconds_count{queue_name=~\"$workqueue\"}[$interval])) by(queue_name)",
       "legendFormat": "{{queue_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}",
       "legendFormat": "resident"
      },
      {
       "expr": "process_virtual_memory_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}",
       "legendFormat": "virtual"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}[$interval])",
       "legendFormat": "resident"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}[$interval])",
       "legendFormat": "virtual"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}[30s])",
       "legendFormat": "alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "go memstats deriv",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}[$interval])",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}[$interval])",
       "legendFormat": "alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}[$interval])",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}[$interval])",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(process_open_fds{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=~\"^($namespace)$\",job=~\"^($job)$\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}