// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"

	predicate "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/storage/predicate"
)

// InstanceLister is an autogenerated mock type for the InstanceLister type
type InstanceLister struct {
	mock.Mock
}

// FindAllJoinedWithOperations provides a mock function with given fields: prct
func (_m *InstanceLister) FindAllJoinedWithOperations(prct ...predicate.Predicate) ([]internal.InstanceWithOperation, error) {
	_va := make([]interface{}, len(prct))
	for _i := range prct {
		_va[_i] = prct[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []internal.InstanceWithOperation
	if rf, ok := ret.Get(0).(func(...predicate.Predicate) []internal.InstanceWithOperation); ok {
		r0 = rf(prct...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.InstanceWithOperation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...predicate.Predicate) error); ok {
		r1 = rf(prct...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
