// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"

	mock "github.com/stretchr/testify/mock"

	orchestration "github.com/kyma-project/control-plane/components/kyma-environment-broker/common/orchestration"
)

// RuntimeResolver is an autogenerated mock type for the RuntimeResolver type
type RuntimeResolver struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: targets
func (_m *RuntimeResolver) Resolve(targets orchestration.TargetSpec) ([]internal.Runtime, error) {
	ret := _m.Called(targets)

	var r0 []internal.Runtime
	if rf, ok := ret.Get(0).(func(orchestration.TargetSpec) []internal.Runtime); ok {
		r0 = rf(targets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.Runtime)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(orchestration.TargetSpec) error); ok {
		r1 = rf(targets)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
