// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"

	mock "github.com/stretchr/testify/mock"

	orchestration "github.com/kyma-project/control-plane/components/kyma-environment-broker/common/orchestration"

	time "time"
)

// Strategy is an autogenerated mock type for the Strategy type
type Strategy struct {
	mock.Mock
}

// Execute provides a mock function with given fields: operations, strategySpec
func (_m *Strategy) Execute(operations []internal.RuntimeOperation, strategySpec orchestration.StrategySpec) (time.Duration, error) {
	ret := _m.Called(operations, strategySpec)

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func([]internal.RuntimeOperation, orchestration.StrategySpec) time.Duration); ok {
		r0 = rf(operations, strategySpec)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]internal.RuntimeOperation, orchestration.StrategySpec) error); ok {
		r1 = rf(operations, strategySpec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
