kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  name: {shoot-name}
spec:
  cloudProfileName: az
  kubernetes:
    allowPrivilegedContainers: true
    kubeAPIServer:
      enableBasicAuthentication: false
    version: 1.16.12
  maintenance:
    autoUpdate:
      kubernetesVersion: false
      machineImageVersion: false
    timeWindow:
      # standard SAP maintenance window for Europe
      begin: 220000+0000
      end: 020000+0000
  networking:
    nodes: 10.250.0.0/19
    type: calico
  provider:
    type: azure
    infrastructureConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vnet:
          cidr: 10.250.0.0/16
        workers: 10.250.0.0/16
      zoned: true
    workers:
        # those depend on the desired workload, default Kyma SKR values are used for this worker group
      - name: cpu-worker-0
        machine:
          type: Standard_D8_v3
          image:
            name: gardenlinux
            version: 27.1.0
        maximum: 10
        minimum: 3
        maxSurge: 4
        maxUnavailable: 1
        volume:
          type: Standard_LRS
          size: 50Gi
        zones:
          - '1'
          - '2'
          - '3'
        systemComponents:
          allow: true
  # this is just an indicator of cluster purpose, not really affecting it's behaviour
  purpose: development
  # examples: northeurope, westeurope, centralus, westus2
  region: {cluster-region}
  secretBindingName: {gardener-secret-name}
  # examples: az-us1 az-eu1 az-us2 az-eu2, best to match region
  seedName: {gardener-seed}