// Code generated by mockery v2.9.4. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"
)

// ComponentsDisabler is an autogenerated mock type for the ComponentsDisabler type
type ComponentsDisabler struct {
	mock.Mock
}

// DisableComponents provides a mock function with given fields: components
func (_m *ComponentsDisabler) DisableComponents(components internal.ComponentConfigurationInputList) (internal.ComponentConfigurationInputList, error) {
	ret := _m.Called(components)

	var r0 internal.ComponentConfigurationInputList
	if rf, ok := ret.Get(0).(func(internal.ComponentConfigurationInputList) internal.ComponentConfigurationInputList); ok {
		r0 = rf(components)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.ComponentConfigurationInputList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(internal.ComponentConfigurationInputList) error); ok {
		r1 = rf(components)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
