// Code generated by mockery v2.3.0. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"
)

// RuntimeVersionConfiguratorForUpgrade is an autogenerated mock type for the RuntimeVersionConfiguratorForUpgrade type
type RuntimeVersionConfiguratorForUpgrade struct {
	mock.Mock
}

// ForUpgrade provides a mock function with given fields:
func (_m *RuntimeVersionConfiguratorForUpgrade) ForUpgrade() *internal.RuntimeVersionData {
	ret := _m.Called()

	var r0 *internal.RuntimeVersionData
	if rf, ok := ret.Get(0).(func() *internal.RuntimeVersionData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.RuntimeVersionData)
		}
	}

	return r0
}
