// Code generated by mockery v2.9.4. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"
)

// StepCondition is an autogenerated mock type for the StepCondition type
type StepCondition struct {
	mock.Mock
}

// Execute provides a mock function with given fields: operation
func (_m *StepCondition) Execute(operation internal.UpgradeKymaOperation) bool {
	ret := _m.Called(operation)

	var r0 bool
	if rf, ok := ret.Get(0).(func(internal.UpgradeKymaOperation) bool); ok {
		r0 = rf(operation)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
