apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  kyma_istio_operator: |-
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      namespace: istio-system
    spec:
      values:
        global:
          proxy:
            resources:
              requests:
                cpu: 20m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 128Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcp-overrides-ory
  namespace: kyma-installer
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
data:
  global.istio.gateway.name: "kyma-gateway"
  global.istio.gateway.namespace: "kyma-system"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: tracing
    kyma-project.io/installation: ""
data:
  global.tracing.enabled: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: core
    kyma-project.io/installation: ""
data:
  test.external_solution.event_mesh.enabled: "false"
