---
apiVersion: v1
kind: Namespace
metadata:
  name: kcp-installer
  labels:
    istio-injection: disabled
    kyma-project.io/installation: ""
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kcp-default
  namespace: kcp-installer
  labels:
    kyma-project.io/installation: ""
spec:
  limits:
  - max:
      memory: 2048Mi # Maximum memory that a container can request
    default:
      # If a container does not specify memory limit, this default value will be applied.
      # If a container tries to allocate more memory, container will be OOM killed.
      memory: 256Mi
    defaultRequest:
      # If a container does not specify memory request, this default value will be applied.
      # The scheduler considers this value when scheduling a container to a node.
      # If a node has not enough memory, such pod will not be created.
      memory: 32Mi
    type: Container
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installations.installer.kyma-project.io
  labels:
    kyma-project.io/installation: ""
spec:
  group: installer.kyma-project.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Installation
    singular: installation
    plural: installations
    shortNames: ['installation']
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: releases.release.kyma-project.io
  labels:
    kyma-project.io/installation: ""
spec:
  group: release.kyma-project.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Release
    singular: release
    plural: releases
    shortNames: ['release']
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: all-psp
rules:
- apiGroups: ["extensions","policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: all-psp
subjects:
- kind: ServiceAccount
  name: helm-certs-job-sa
  namespace: kcp-installer
roleRef:
  kind: ClusterRole
  name: all-psp
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcp-installer
  namespace: kcp-installer
  labels:
    kyma-project.io/installation: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcp-installer
  namespace: kcp-installer
  labels:
    kyma-project.io/installation: ""
spec:
  selector:
    matchLabels:
      name: kcp-installer
  # Installer is designed to be run as a single instance only
  # We enforce it by changing default rolling update to recreate startegy.
  # With that k8s will first delete old pod and then provision new one during upgrade.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: kcp-installer
    spec:
      serviceAccountName: kcp-installer
      containers:
      - name: kcp-installer-container
        image: eu.gcr.io/kyma-project/develop/installer:408cb6a6
        imagePullPolicy: IfNotPresent
        env:
          - name: INST_RESOURCE
            value: "kcp-installation"
          - name: OVERRIDES_NAMESPACE
            value: "kcp-installer"
        args:
          - -overrideLogFile=/app/overrides.txt
          - -helmDebugMode=true
        resources:
          requests:
            memory: 32Mi
            cpu: 40m
          limits:
            memory: 2Gi
            cpu: 400m
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kcp-installer-reader
  labels:
    kyma-project.io/installation: ""
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kcp-installer
  labels:
    kyma-project.io/installation: ""
subjects:
- kind: ServiceAccount
  name: kcp-installer
  namespace: kcp-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-installer-reader
