// Code generated by mockery v1.1.2. DO NOT EDIT.

package automock

import (
	runtime "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/runtime"
	mock "github.com/stretchr/testify/mock"
)

// ComponentListProvider is an autogenerated mock type for the ComponentListProvider type
type ComponentListProvider struct {
	mock.Mock
}

// AllComponents provides a mock function with given fields: kymaVersion
func (_m *ComponentListProvider) AllComponents(kymaVersion string) (runtime.ComponentListData, error) {
	ret := _m.Called(kymaVersion)

	var r0 runtime.ComponentListData
	if rf, ok := ret.Get(0).(func(string) runtime.ComponentListData); ok {
		r0 = rf(kymaVersion)
	} else {
		r0 = ret.Get(0).(runtime.ComponentListData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(kymaVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
