// Code generated by mockery v2.12.2. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"
	mock "github.com/stretchr/testify/mock"

	runtime "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/runtime"

	testing "testing"
)

// ComponentListProvider is an autogenerated mock type for the ComponentListProvider type
type ComponentListProvider struct {
	mock.Mock
}

// AllComponents provides a mock function with given fields: kymaVersion
func (_m *ComponentListProvider) AllComponents(kymaVersion internal.RuntimeVersionData) ([]runtime.KymaComponent, error) {
	ret := _m.Called(kymaVersion)

	var r0 []runtime.KymaComponent
	if rf, ok := ret.Get(0).(func(internal.RuntimeVersionData) []runtime.KymaComponent); ok {
		r0 = rf(kymaVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]runtime.KymaComponent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(internal.RuntimeVersionData) error); ok {
		r1 = rf(kymaVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewComponentListProvider creates a new instance of ComponentListProvider. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewComponentListProvider(t testing.TB) *ComponentListProvider {
	mock := &ComponentListProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
