// Code generated by mockery v2.9.4. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// DisabledComponentsProvider is an autogenerated mock type for the DisabledComponentsProvider type
type DisabledComponentsProvider struct {
	mock.Mock
}

// DisabledComponentsPerPlan provides a mock function with given fields: planID
func (_m *DisabledComponentsProvider) DisabledComponentsPerPlan(planID string) (map[string]struct{}, error) {
	ret := _m.Called(planID)

	var r0 map[string]struct{}
	if rf, ok := ret.Get(0).(func(string) map[string]struct{}); ok {
		r0 = rf(planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]struct{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisabledForAll provides a mock function with given fields:
func (_m *DisabledComponentsProvider) DisabledForAll() map[string]struct{} {
	ret := _m.Called()

	var r0 map[string]struct{}
	if rf, ok := ret.Get(0).(func() map[string]struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]struct{})
		}
	}

	return r0
}
