apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ template "kyma-metrics-collector.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  mtls:
    mode: PERMISSIVE
