{{- if .Values.global.kyma_metrics_collector.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kyma-metrics-collector.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
{{ include "kyma-metrics-collector.labels" . | indent 4 }}
type: Opaque
data:
  token: {{ .Values.edp.token | b64enc | quote }}
{{- end -}}
