{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kyma-metrics-collector.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
{{ include "kyma-metrics-collector.labels" . | indent 4 }}
{{- end }}