apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcp-monitoring
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: ["operator.victoriametrics.com"]
    resources: ["vmrules"]
    verbs: ["*"]
  - apiGroups: ["operator.victoriametrics.com"]
    resources: ["vmusers"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcp-monitoring
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.kyma_environment_broker.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kcp-monitoring
  apiGroup: rbac.authorization.k8s.io
