apiVersion: v1
kind: ConfigMap
metadata:
  name: global-overrides
  namespace: {{ .Release.Namespace }}
  labels:
    provisioning-runtime-override: "true"
data:
  global.disableLegacyConnectivity: "true"
