{{- if eq .Values.manageSecrets true }}
apiVersion: v1
data:
  apiEndpoint: {{ .Values.avs.apiEndpoint | b64enc | quote }}
  apiKey: {{ .Values.avs.apiKey | b64enc | quote }}
  clientId: {{ .Values.avs.clientId | b64enc | quote }}
  oauthPassword: {{ .Values.avs.oauthPassword | b64enc | quote }}
  oauthTokenEndpoint: {{ .Values.avs.oauthTokenEndpoint | b64enc | quote }}
  oauthUserName: {{ .Values.avs.oauthUserName | b64enc | quote }}
  internalTesterAccessId: {{ .Values.avs.internalTesterAccessId | b64enc | quote }}
  externalTesterAccessId: {{ .Values.avs.externalTesterAccessId | b64enc | quote }}
  internalTesterService: {{ .Values.avs.internalTesterService | b64enc | quote }}
  externalTesterService: {{ .Values.avs.externalTesterService | b64enc | quote }}
  internalTesterTags: {{ include "avs.utils.joinTags" .Values.avs.internalTesterTags | b64enc | quote }}
  externalTesterTags: {{ include "avs.utils.joinTags" .Values.avs.externalTesterTags | b64enc | quote }}
  groupId: {{ .Values.avs.groupId | b64enc | quote }}
  parentId: {{ .Values.avs.parentId | b64enc | quote }}
  trialApiKey: {{ .Values.avs.trialApiKey | b64enc | quote }}
  trialInternalTesterAccessId: {{ .Values.avs.trialInternalTesterAccessId | b64enc | quote }}
  trialGroupId: {{ .Values.avs.trialGroupId | b64enc | quote }}
  trialParentId: {{ .Values.avs.trialParentId | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.avs.secretName }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.ias.secretName }}"
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.ias.id | b64enc | quote }}
  secret: {{ .Values.ias.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.edp.secretName }}"
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.edp.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.cis.v1.secretName }}"
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.v1.id | b64enc | quote }}
  secret: {{ .Values.cis.v1.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.cis.v2.secretName }}"
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.v2.id | b64enc | quote }}
  secret: {{ .Values.cis.v2.secret | b64enc | quote }}
{{- end }}
