// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import (
	autorest "github.com/Azure/go-autorest/autorest"
	azure "github.com/Azure/go-autorest/autorest/azure"

	mock "github.com/stretchr/testify/mock"
)

// AuthConfig is an autogenerated mock type for the AuthConfig type
type AuthConfig struct {
	mock.Mock
}

// GetAuthConfig provides a mock function with given fields: clientID, clientSecret, tenantID, envName
func (_m *AuthConfig) GetAuthConfig(clientID string, clientSecret string, tenantID string, envName string) (autorest.Authorizer, azure.Environment, error) {
	ret := _m.Called(clientID, clientSecret, tenantID, envName)

	var r0 autorest.Authorizer
	if rf, ok := ret.Get(0).(func(string, string, string, string) autorest.Authorizer); ok {
		r0 = rf(clientID, clientSecret, tenantID, envName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(autorest.Authorizer)
		}
	}

	var r1 azure.Environment
	if rf, ok := ret.Get(1).(func(string, string, string, string) azure.Environment); ok {
		r1 = rf(clientID, clientSecret, tenantID, envName)
	} else {
		r1 = ret.Get(1).(azure.Environment)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, string, string) error); ok {
		r2 = rf(clientID, clientSecret, tenantID, envName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
