{{ if .Values.global.mothership_reconciler.authentication }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: cloudsql-proxy
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      {{- include "cloudsql-proxy.labels" . | nindent 6 }}
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.global.mothership_reconciler.serviceAccountName }}"]
{{- end }}