apiVersion: v1
kind: Service
metadata:
  name: rma-reconciler
  namespace: {{ .Release.Namespace }}
  labels:
    kyma-project.io/component-reconciler: ""
    component: rma
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.istioPort }}
      targetPort: {{ .Values.service.istioPort }}
      protocol: TCP
      name: istio-http
  selector:
    kyma-project.io/component-reconciler: ""
    component: rma
