{{ if $.Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: rma
  name: rma-reconciler
  namespace: {{ $.Release.Namespace }}
spec:
  endpoints:
  - port: http
    interval: {{ $.Values.serviceMonitor.interval }}
    scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      component: rma
{{- end }}
