// Code generated by mockery v1.1.2. DO NOT EDIT.

package automock

import (
	internal "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal"

	mock "github.com/stretchr/testify/mock"
)

// KcBuilder is an autogenerated mock type for the KcBuilder type
type KcBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: _a0
func (_m *KcBuilder) Build(_a0 *internal.Instance) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(*internal.Instance) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*internal.Instance) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
