apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    release: redis
  name: redis-ext
  namespace: redis1-system
spec:
  ports:
  - nodePort: 30000
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    release: redis
    role: master
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    release: redis
  name: redis-ext
  namespace: redis2-system
spec:
  ports:
  - nodePort: 31000
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    release: redis
    role: master
  type: NodePort
