// Code generated by mockery v2.6.0. DO NOT EDIT.

package automock

import (
	cls "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/cls"
	logrus "github.com/sirupsen/logrus"

	mock "github.com/stretchr/testify/mock"

	servicemanager "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/servicemanager"
)

// ClsProvisioner is an autogenerated mock type for the ClsProvisioner type
type ClsProvisioner struct {
	mock.Mock
}

// Provision provides a mock function with given fields: log, smClient, request
func (_m *ClsProvisioner) Provision(log logrus.FieldLogger, smClient servicemanager.Client, request *cls.ProvisionRequest) (*cls.ProvisionResult, error) {
	ret := _m.Called(log, smClient, request)

	var r0 *cls.ProvisionResult
	if rf, ok := ret.Get(0).(func(logrus.FieldLogger, servicemanager.Client, *cls.ProvisionRequest) *cls.ProvisionResult); ok {
		r0 = rf(log, smClient, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cls.ProvisionResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(logrus.FieldLogger, servicemanager.Client, *cls.ProvisionRequest) error); ok {
		r1 = rf(log, smClient, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
