// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package automock

import (
	cls "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/cls"
	mock "github.com/stretchr/testify/mock"

	servicemanager "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/servicemanager"
)

// ClsInstanceProvider is an autogenerated mock type for the ClsInstanceProvider type
type ClsInstanceProvider struct {
	mock.Mock
}

// ProvisionIfNoneExists provides a mock function with given fields: smClient, request
func (_m *ClsInstanceProvider) ProvisionIfNoneExists(smClient servicemanager.Client, request *cls.ProvisionRequest) (*cls.ProvisionResult, error) {
	ret := _m.Called(smClient, request)

	var r0 *cls.ProvisionResult
	if rf, ok := ret.Get(0).(func(servicemanager.Client, *cls.ProvisionRequest) *cls.ProvisionResult); ok {
		r0 = rf(smClient, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cls.ProvisionResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(servicemanager.Client, *cls.ProvisionRequest) error); ok {
		r1 = rf(smClient, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
