// Code generated by mockery v2.6.0. DO NOT EDIT.

package automock

import (
	cls "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/cls"
	logrus "github.com/sirupsen/logrus"

	mock "github.com/stretchr/testify/mock"

	servicemanager "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/servicemanager"
)

// ClsStatusChecker is an autogenerated mock type for the ClsStatusChecker type
type ClsStatusChecker struct {
	mock.Mock
}

// CheckProvisionStatus provides a mock function with given fields: smClient, instanceKey, log
func (_m *ClsStatusChecker) CheckProvisionStatus(smClient servicemanager.Client, instanceKey servicemanager.InstanceKey, log logrus.FieldLogger) (cls.ProvisionStatus, error) {
	ret := _m.Called(smClient, instanceKey, log)

	var r0 cls.ProvisionStatus
	if rf, ok := ret.Get(0).(func(servicemanager.Client, servicemanager.InstanceKey, logrus.FieldLogger) cls.ProvisionStatus); ok {
		r0 = rf(smClient, instanceKey, log)
	} else {
		r0 = ret.Get(0).(cls.ProvisionStatus)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(servicemanager.Client, servicemanager.InstanceKey, logrus.FieldLogger) error); ok {
		r1 = rf(smClient, instanceKey, log)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
