// Code generated by mockery v2.14.0. DO NOT EDIT.

package automock

import (
	edp "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/edp"
	mock "github.com/stretchr/testify/mock"
)

// EDPClient is an autogenerated mock type for the EDPClient type
type EDPClient struct {
	mock.Mock
}

// CreateDataTenant provides a mock function with given fields: data
func (_m *EDPClient) CreateDataTenant(data edp.DataTenantPayload) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(edp.DataTenantPayload) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMetadataTenant provides a mock function with given fields: name, env, data
func (_m *EDPClient) CreateMetadataTenant(name string, env string, data edp.MetadataTenantPayload) error {
	ret := _m.Called(name, env, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, edp.MetadataTenantPayload) error); ok {
		r0 = rf(name, env, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDataTenant provides a mock function with given fields: name, env
func (_m *EDPClient) DeleteDataTenant(name string, env string) error {
	ret := _m.Called(name, env)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, env)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMetadataTenant provides a mock function with given fields: name, env, key
func (_m *EDPClient) DeleteMetadataTenant(name string, env string, key string) error {
	ret := _m.Called(name, env, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, env, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEDPClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewEDPClient creates a new instance of EDPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEDPClient(t mockConstructorTestingTNewEDPClient) *EDPClient {
	mock := &EDPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
