// Code generated by mockery v2.6.0. DO NOT EDIT.

package automock

import (
	cls "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/cls"

	logrus "github.com/sirupsen/logrus"

	mock "github.com/stretchr/testify/mock"

	servicemanager "github.com/kyma-project/control-plane/components/kyma-environment-broker/internal/servicemanager"
)

// ClsDeprovisioner is an autogenerated mock type for the ClsDeprovisioner type
type ClsDeprovisioner struct {
	mock.Mock
}

// Deprovision provides a mock function with given fields: smClient, request, log
func (_m *ClsDeprovisioner) Deprovision(smClient servicemanager.Client, request *cls.DeprovisionRequest, log logrus.FieldLogger) (*cls.DeprovisionResult, error) {
	ret := _m.Called(smClient, request, log)

	var r0 *cls.DeprovisionResult
	if rf, ok := ret.Get(0).(func(servicemanager.Client, *cls.DeprovisionRequest, logrus.FieldLogger) *cls.DeprovisionResult); ok {
		r0 = rf(smClient, request, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cls.DeprovisionResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(servicemanager.Client, *cls.DeprovisionRequest, logrus.FieldLogger) error); ok {
		r1 = rf(smClient, request, log)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
