// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/control-plane/components/provisioner/internal/apperrors"
	dbsession "github.com/kyma-project/control-plane/components/provisioner/internal/provisioning/persistence/dbsession"
	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-project/control-plane/components/provisioner/internal/model"

	time "time"
)

// ReadWriteSession is an autogenerated mock type for the ReadWriteSession type
type ReadWriteSession struct {
	mock.Mock
}

// DeleteCluster provides a mock function with given fields: runtimeID
func (_m *ReadWriteSession) DeleteCluster(runtimeID string) apperrors.AppError {
	ret := _m.Called(runtimeID)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string) apperrors.AppError); ok {
		r0 = rf(runtimeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// FixShootProvisioningStage provides a mock function with given fields: message, newStage, transitionTime
func (_m *ReadWriteSession) FixShootProvisioningStage(message string, newStage model.OperationStage, transitionTime time.Time) apperrors.AppError {
	ret := _m.Called(message, newStage, transitionTime)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, model.OperationStage, time.Time) apperrors.AppError); ok {
		r0 = rf(message, newStage, transitionTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// GetCluster provides a mock function with given fields: runtimeID
func (_m *ReadWriteSession) GetCluster(runtimeID string) (model.Cluster, apperrors.AppError) {
	ret := _m.Called(runtimeID)

	var r0 model.Cluster
	if rf, ok := ret.Get(0).(func(string) model.Cluster); ok {
		r0 = rf(runtimeID)
	} else {
		r0 = ret.Get(0).(model.Cluster)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(runtimeID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetGardenerClusterByName provides a mock function with given fields: name
func (_m *ReadWriteSession) GetGardenerClusterByName(name string) (model.Cluster, apperrors.AppError) {
	ret := _m.Called(name)

	var r0 model.Cluster
	if rf, ok := ret.Get(0).(func(string) model.Cluster); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(model.Cluster)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetLastOperation provides a mock function with given fields: runtimeID
func (_m *ReadWriteSession) GetLastOperation(runtimeID string) (model.Operation, apperrors.AppError) {
	ret := _m.Called(runtimeID)

	var r0 model.Operation
	if rf, ok := ret.Get(0).(func(string) model.Operation); ok {
		r0 = rf(runtimeID)
	} else {
		r0 = ret.Get(0).(model.Operation)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(runtimeID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetOperation provides a mock function with given fields: operationID
func (_m *ReadWriteSession) GetOperation(operationID string) (model.Operation, apperrors.AppError) {
	ret := _m.Called(operationID)

	var r0 model.Operation
	if rf, ok := ret.Get(0).(func(string) model.Operation); ok {
		r0 = rf(operationID)
	} else {
		r0 = ret.Get(0).(model.Operation)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(operationID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetProviderSpecificConfigsByProvider provides a mock function with given fields: provider
func (_m *ReadWriteSession) GetProviderSpecificConfigsByProvider(provider string) ([]dbsession.ProviderData, apperrors.AppError) {
	ret := _m.Called(provider)

	var r0 []dbsession.ProviderData
	if rf, ok := ret.Get(0).(func(string) []dbsession.ProviderData); ok {
		r0 = rf(provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbsession.ProviderData)
		}
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(provider)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetRuntimeUpgrade provides a mock function with given fields: operationId
func (_m *ReadWriteSession) GetRuntimeUpgrade(operationId string) (model.RuntimeUpgrade, apperrors.AppError) {
	ret := _m.Called(operationId)

	var r0 model.RuntimeUpgrade
	if rf, ok := ret.Get(0).(func(string) model.RuntimeUpgrade); ok {
		r0 = rf(operationId)
	} else {
		r0 = ret.Get(0).(model.RuntimeUpgrade)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(operationId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetTenant provides a mock function with given fields: runtimeID
func (_m *ReadWriteSession) GetTenant(runtimeID string) (string, apperrors.AppError) {
	ret := _m.Called(runtimeID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(runtimeID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(runtimeID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetTenantForOperation provides a mock function with given fields: operationID
func (_m *ReadWriteSession) GetTenantForOperation(operationID string) (string, apperrors.AppError) {
	ret := _m.Called(operationID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(operationID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(operationID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetUpdatedProviderSpecificConfigByID provides a mock function with given fields: id
func (_m *ReadWriteSession) GetUpdatedProviderSpecificConfigByID(id string) (string, apperrors.AppError) {
	ret := _m.Called(id)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(string) apperrors.AppError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// InProgressOperationsCount provides a mock function with given fields:
func (_m *ReadWriteSession) InProgressOperationsCount() (model.OperationsCount, apperrors.AppError) {
	ret := _m.Called()

	var r0 model.OperationsCount
	if rf, ok := ret.Get(0).(func() model.OperationsCount); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.OperationsCount)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func() apperrors.AppError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// InsertAdministrators provides a mock function with given fields: clusterId, administrators
func (_m *ReadWriteSession) InsertAdministrators(clusterId string, administrators []string) apperrors.AppError {
	ret := _m.Called(clusterId, administrators)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, []string) apperrors.AppError); ok {
		r0 = rf(clusterId, administrators)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// InsertCluster provides a mock function with given fields: cluster
func (_m *ReadWriteSession) InsertCluster(cluster model.Cluster) apperrors.AppError {
	ret := _m.Called(cluster)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(model.Cluster) apperrors.AppError); ok {
		r0 = rf(cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// InsertGardenerConfig provides a mock function with given fields: config
func (_m *ReadWriteSession) InsertGardenerConfig(config model.GardenerConfig) apperrors.AppError {
	ret := _m.Called(config)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(model.GardenerConfig) apperrors.AppError); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// InsertKymaConfig provides a mock function with given fields: kymaConfig
func (_m *ReadWriteSession) InsertKymaConfig(kymaConfig model.KymaConfig) apperrors.AppError {
	ret := _m.Called(kymaConfig)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(model.KymaConfig) apperrors.AppError); ok {
		r0 = rf(kymaConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// InsertOperation provides a mock function with given fields: operation
func (_m *ReadWriteSession) InsertOperation(operation model.Operation) apperrors.AppError {
	ret := _m.Called(operation)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(model.Operation) apperrors.AppError); ok {
		r0 = rf(operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// InsertRelease provides a mock function with given fields: artifacts
func (_m *ReadWriteSession) InsertRelease(artifacts model.Release) apperrors.AppError {
	ret := _m.Called(artifacts)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(model.Release) apperrors.AppError); ok {
		r0 = rf(artifacts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// InsertRuntimeUpgrade provides a mock function with given fields: runtimeUpgrade
func (_m *ReadWriteSession) InsertRuntimeUpgrade(runtimeUpgrade model.RuntimeUpgrade) apperrors.AppError {
	ret := _m.Called(runtimeUpgrade)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(model.RuntimeUpgrade) apperrors.AppError); ok {
		r0 = rf(runtimeUpgrade)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// ListInProgressOperations provides a mock function with given fields:
func (_m *ReadWriteSession) ListInProgressOperations() ([]model.Operation, apperrors.AppError) {
	ret := _m.Called()

	var r0 []model.Operation
	if rf, ok := ret.Get(0).(func() []model.Operation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Operation)
		}
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func() apperrors.AppError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// MarkClusterAsDeleted provides a mock function with given fields: runtimeID
func (_m *ReadWriteSession) MarkClusterAsDeleted(runtimeID string) apperrors.AppError {
	ret := _m.Called(runtimeID)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string) apperrors.AppError); ok {
		r0 = rf(runtimeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// SetActiveKymaConfig provides a mock function with given fields: runtimeID, kymaConfigId
func (_m *ReadWriteSession) SetActiveKymaConfig(runtimeID string, kymaConfigId string) apperrors.AppError {
	ret := _m.Called(runtimeID, kymaConfigId)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string) apperrors.AppError); ok {
		r0 = rf(runtimeID, kymaConfigId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// TransitionOperation provides a mock function with given fields: operationID, message, stage, transitionTime
func (_m *ReadWriteSession) TransitionOperation(operationID string, message string, stage model.OperationStage, transitionTime time.Time) apperrors.AppError {
	ret := _m.Called(operationID, message, stage, transitionTime)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string, model.OperationStage, time.Time) apperrors.AppError); ok {
		r0 = rf(operationID, message, stage, transitionTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// UpdateGardenerClusterConfig provides a mock function with given fields: config
func (_m *ReadWriteSession) UpdateGardenerClusterConfig(config model.GardenerConfig) apperrors.AppError {
	ret := _m.Called(config)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(model.GardenerConfig) apperrors.AppError); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// UpdateKubeconfig provides a mock function with given fields: runtimeID, kubeconfig
func (_m *ReadWriteSession) UpdateKubeconfig(runtimeID string, kubeconfig string) apperrors.AppError {
	ret := _m.Called(runtimeID, kubeconfig)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string) apperrors.AppError); ok {
		r0 = rf(runtimeID, kubeconfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// UpdateKubernetesVersion provides a mock function with given fields: runtimeID, version
func (_m *ReadWriteSession) UpdateKubernetesVersion(runtimeID string, version string) apperrors.AppError {
	ret := _m.Called(runtimeID, version)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string) apperrors.AppError); ok {
		r0 = rf(runtimeID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// UpdateOperationLastError provides a mock function with given fields: operationID, msg, reason, component
func (_m *ReadWriteSession) UpdateOperationLastError(operationID string, msg string, reason string, component string) apperrors.AppError {
	ret := _m.Called(operationID, msg, reason, component)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string, string, string) apperrors.AppError); ok {
		r0 = rf(operationID, msg, reason, component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// UpdateOperationState provides a mock function with given fields: operationID, message, state, endTime
func (_m *ReadWriteSession) UpdateOperationState(operationID string, message string, state model.OperationState, endTime time.Time) apperrors.AppError {
	ret := _m.Called(operationID, message, state, endTime)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string, model.OperationState, time.Time) apperrors.AppError); ok {
		r0 = rf(operationID, message, state, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// UpdateProviderSpecificConfig provides a mock function with given fields: id, providerSpecificConfig
func (_m *ReadWriteSession) UpdateProviderSpecificConfig(id string, providerSpecificConfig string) apperrors.AppError {
	ret := _m.Called(id, providerSpecificConfig)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string) apperrors.AppError); ok {
		r0 = rf(id, providerSpecificConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// UpdateTenant provides a mock function with given fields: runtimeID, tenant
func (_m *ReadWriteSession) UpdateTenant(runtimeID string, tenant string) apperrors.AppError {
	ret := _m.Called(runtimeID, tenant)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string) apperrors.AppError); ok {
		r0 = rf(runtimeID, tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}

// UpdateUpgradeState provides a mock function with given fields: operationID, upgradeState
func (_m *ReadWriteSession) UpdateUpgradeState(operationID string, upgradeState model.UpgradeState) apperrors.AppError {
	ret := _m.Called(operationID, upgradeState)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, model.UpgradeState) apperrors.AppError); ok {
		r0 = rf(operationID, upgradeState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}
