apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
        daprTest: test
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "nodeapp"
        dapr.io/port: "3000"
    spec:
      containers:
      - name: node
        image: dapriosamples/hello-k8s-node:0.9.0
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nodeapp
    annotations:
        ingress.kubernetes.io/ssl-redirect: "false"
spec:
    rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: nodeapp
            servicePort: 80